import { Document, DocumentCategory } from '@/types'

export let documents: Document[] = [
  {
    id: 'doc_001',
    name: 'Lease Agreement - Sarah Mitchell - Unit 101',
    category: DocumentCategory.LEASE,
    url: '/mock-docs/doc_001.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 245760,
    propertyId: 'prop_rv1',
    unitId: 'unit_rv1_101',
    tenantId: 'tenant_001',
    leaseId: 'lease_001',
    uploadedBy: 'user_manager_001',
    createdAt: new Date('2026-08-01'),
  },
  {
    id: 'doc_002',
    name: 'Move-In Inspection - Unit 101',
    category: DocumentCategory.INSPECTION,
    url: '/mock-docs/doc_002.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 184320,
    propertyId: 'prop_rv1',
    unitId: 'unit_rv1_101',
    tenantId: 'tenant_001',
    uploadedBy: 'user_manager_001',
    createdAt: new Date('2026-08-01'),
  },
  {
    id: 'doc_003',
    name: 'Lease Agreement - Jordan Hayes - Unit 201',
    category: DocumentCategory.LEASE,
    url: '/mock-docs/doc_003.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 251904,
    propertyId: 'prop_rv1',
    unitId: 'unit_rv1_201',
    tenantId: 'tenant_002',
    leaseId: 'lease_002',
    uploadedBy: 'user_manager_001',
    createdAt: new Date('2026-08-01'),
  },
  {
    id: 'doc_004',
    name: 'Payment Receipt - September 2026 - tenant_001',
    category: DocumentCategory.RECEIPT,
    url: '/mock-docs/doc_004.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 51200,
    tenantId: 'tenant_001',
    leaseId: 'lease_001',
    uploadedBy: 'user_manager_001',
    createdAt: new Date('2026-09-01'),
  },
  {
    id: 'doc_005',
    name: 'Property Photo - Richland Village Exterior',
    category: DocumentCategory.PHOTO,
    url: '/mock-docs/doc_005.pdf',
    mimeType: 'image/jpeg',
    sizeBytes: 2097152,
    propertyId: 'prop_rv1',
    uploadedBy: 'user_manager_001',
    createdAt: new Date('2024-01-15'),
  },
]
