import { Lead, LeadSource } from '@/types'

// 8 leads inquiring about Fall 2027 units across all four properties

export let leads: Lead[] = [
  {
    id: 'lead_001',
    name: 'Connor Blackwell',
    email: 'cblackwell@auburn.edu',
    phone: '(334) 555-5001',
    propertyId: 'prop_rv3',
    unitId: 'unit_rv3_4a',
    source: LeadSource.WEBSITE,
    notes: 'Interested in a 4BD unit with roommates for fall. Wants to know about parking availability and utility costs. Has toured once already — good prospect.',
    status: 'TOURED',
    createdAt: new Date('2026-08-15T10:00:00'),
  },
  {
    id: 'lead_002',
    name: 'Aisha Thompson',
    email: 'aisha.t@gmail.com',
    phone: '(205) 555-5002',
    propertyId: 'prop_bab',
    source: LeadSource.ZILLOW,
    notes: 'Inquired about B-05 or B-06. First-year grad student looking for quiet neighborhood. Has not yet scheduled a tour.',
    status: 'CONTACTED',
    createdAt: new Date('2026-08-20T14:30:00'),
  },
  {
    id: 'lead_003',
    name: 'Jake Merritt',
    email: 'jake.merritt25@yahoo.com',
    phone: '(256) 555-5003',
    propertyId: 'prop_rv1',
    unitId: 'unit_rv1_302',
    source: LeadSource.REFERRAL,
    notes: 'Referred by current tenant Jordan Hayes (tenant_002). Interested in 4BD Kensington. Tour scheduled Sept 10.',
    status: 'TOURED',
    createdAt: new Date('2026-08-28T09:15:00'),
  },
  {
    id: 'lead_004',
    name: 'Samantha Reeves',
    email: 'sreeves@auburn.edu',
    phone: '(334) 555-5004',
    propertyId: 'prop_jac',
    unitId: 'unit_jac_a04',
    source: LeadSource.APARTMENTS_COM,
    notes: 'Interested in a Cottage A unit — 3BD. Looking to move in August 2027. Has roommates lined up. Requested application link.',
    status: 'APPLIED',
    createdAt: new Date('2026-09-01T11:00:00'),
  },
  {
    id: 'lead_005',
    name: 'Devon Park',
    email: 'devonpark@icloud.com',
    phone: '(334) 555-5005',
    propertyId: 'prop_rv3',
    unitId: 'unit_rv3_3b',
    source: LeadSource.WEBSITE,
    notes: 'International student — inquired about 3BD unit. Wants to know if a co-signer outside the US is acceptable. Awaiting manager response.',
    status: 'NEW',
    createdAt: new Date('2026-09-04T16:45:00'),
  },
  {
    id: 'lead_006',
    name: 'Brittany Holloway',
    email: 'bholloway@gmail.com',
    phone: '(205) 555-5006',
    propertyId: 'prop_bab',
    unitId: 'unit_bab_b07',
    source: LeadSource.WALK_IN,
    notes: 'Walked in to office Sept 3. Very interested in brownstone — wants the end unit. Works part-time and has parental guarantor. Toured B-07.',
    status: 'TOURED',
    createdAt: new Date('2026-09-03T13:00:00'),
  },
  {
    id: 'lead_007',
    name: 'Nolan Fischer',
    email: 'nfischer99@outlook.com',
    phone: '(334) 555-5007',
    propertyId: 'prop_jac',
    unitId: 'unit_jac_b03',
    source: LeadSource.ZILLOW,
    notes: 'Interested in 2BD Cottage B — wants quiet, off-campus feel. Already emailed back for pricing. Has not scheduled tour yet.',
    status: 'CONTACTED',
    createdAt: new Date('2026-09-02T08:30:00'),
  },
  {
    id: 'lead_008',
    name: 'Gabrielle Okafor',
    email: 'gokafor@auburn.edu',
    phone: '(334) 555-5008',
    propertyId: 'prop_rv1',
    unitId: 'unit_rv1_303',
    source: LeadSource.REFERRAL,
    notes: 'Referred by a faculty member at Auburn. Looking for premium 4BD/4.5BA Kensington unit. Very strong rental history — prior manager gave glowing reference. High priority prospect.',
    status: 'CONTACTED',
    createdAt: new Date('2026-09-05T07:00:00'),
  },
]
