import { MaintenanceRequest, MaintenancePriority, MaintenanceStatus } from '@/types'

export let maintenanceRequests: MaintenanceRequest[] = [
  // ── EMERGENCY (1) ───────────────────────────────────────────────────────────
  {
    id: 'maint_001',
    unitId: 'unit_bab_b02',
    requestedBy: 'tenant_007',
    title: 'Burst pipe under kitchen sink — active water leak',
    description:
      'Water is actively spraying from the pipe connection under the kitchen sink. Water is pooling on the floor and spreading toward the hallway. I have turned off the water valve beneath the sink but need immediate repair.',
    priority: MaintenancePriority.EMERGENCY,
    status: MaintenanceStatus.IN_PROGRESS,
    category: 'Plumbing',
    vendorId: 'vendor_001',
    scheduledAt: new Date('2026-09-05T09:00:00'),
    estimatedCost: 350,
    notes: 'Auburn Plumbing Co. dispatched — arriving 9 AM Sept 5. Water valve shut off by tenant.',
    createdAt: new Date('2026-09-05T07:42:00'),
    updatedAt: new Date('2026-09-05T08:15:00'),
  },

  // ── HIGH (3) ────────────────────────────────────────────────────────────────
  {
    id: 'maint_002',
    unitId: 'unit_rv1_201',
    requestedBy: 'tenant_003',
    title: 'HVAC not cooling — thermostat reading 81°F',
    description:
      'The AC unit is running but not cooling. The thermostat is set to 70°F and it\'s reading 81°F inside. Outside temp is 95°F. This is a health concern — I have roommates with asthma.',
    priority: MaintenancePriority.HIGH,
    status: MaintenanceStatus.IN_PROGRESS,
    category: 'HVAC',
    vendorId: 'vendor_003',
    scheduledAt: new Date('2026-09-06T10:00:00'),
    estimatedCost: 250,
    notes: 'Capital HVAC scheduled for Sept 6. Possible refrigerant recharge needed.',
    createdAt: new Date('2026-09-04T14:22:00'),
    updatedAt: new Date('2026-09-04T16:00:00'),
  },
  {
    id: 'maint_003',
    unitId: 'unit_jac_a01',
    requestedBy: 'tenant_010',
    title: 'Electrical outlet sparking in master bedroom',
    description:
      'The outlet on the east wall of the master bedroom sparks when I plug anything into it. The outlet is warm to the touch. I have stopped using it but am concerned about fire risk.',
    priority: MaintenancePriority.HIGH,
    status: MaintenanceStatus.OPEN,
    category: 'Electrical',
    vendorId: 'vendor_002',
    estimatedCost: 180,
    notes: 'Lee County Electric contacted — awaiting scheduling.',
    createdAt: new Date('2026-09-03T19:05:00'),
    updatedAt: new Date('2026-09-03T19:05:00'),
  },
  {
    id: 'maint_004',
    unitId: 'unit_rv3_2a',
    requestedBy: 'tenant_003',
    title: 'Water heater producing lukewarm water only',
    description:
      'Hot water heater is not heating to full temperature. Showers are only lukewarm even after running for 10+ minutes. Unit is less than a year old — may be a faulty heating element.',
    priority: MaintenancePriority.HIGH,
    status: MaintenanceStatus.OPEN,
    category: 'Plumbing',
    vendorId: 'vendor_001',
    estimatedCost: 200,
    createdAt: new Date('2026-09-02T11:30:00'),
    updatedAt: new Date('2026-09-02T11:30:00'),
  },

  // ── MEDIUM (6) ──────────────────────────────────────────────────────────────
  {
    id: 'maint_005',
    unitId: 'unit_rv1_101',
    requestedBy: 'tenant_001',
    title: 'Dishwasher not draining — standing water at bottom',
    description:
      'After every cycle there is about 2 inches of standing water in the bottom of the dishwasher. Dishes are not getting clean. Has been happening for about a week.',
    priority: MaintenancePriority.MEDIUM,
    status: MaintenanceStatus.IN_PROGRESS,
    category: 'Appliance',
    vendorId: 'vendor_007',
    scheduledAt: new Date('2026-09-07T13:00:00'),
    estimatedCost: 150,
    notes: 'Eagle Appliance Repair scheduled for Sept 7. Likely clogged drain pump.',
    createdAt: new Date('2026-09-01T09:15:00'),
    updatedAt: new Date('2026-09-04T10:00:00'),
  },
  {
    id: 'maint_006',
    unitId: 'unit_jac_b01',
    requestedBy: 'tenant_011',
    title: 'Front door lock sticking — difficult to turn key',
    description:
      'The front door deadbolt has been very stiff and difficult to operate. Sometimes takes 2-3 tries to turn the key. Concerned about security and being locked out.',
    priority: MaintenancePriority.MEDIUM,
    status: MaintenanceStatus.OPEN,
    category: 'General',
    estimatedCost: 75,
    createdAt: new Date('2026-08-28T16:40:00'),
    updatedAt: new Date('2026-08-28T16:40:00'),
  },
  {
    id: 'maint_007',
    unitId: 'unit_bab_b01',
    requestedBy: 'tenant_006',
    title: 'Bathroom exhaust fan making loud rattling noise',
    description:
      'The exhaust fan in the master bath makes a loud rattling noise whenever it runs. It started about 2 weeks ago and is getting worse. Also smells slightly burnt.',
    priority: MaintenancePriority.MEDIUM,
    status: MaintenanceStatus.COMPLETED,
    category: 'Electrical',
    vendorId: 'vendor_004',
    scheduledAt: new Date('2026-08-25T09:00:00'),
    completedAt: new Date('2026-08-25T11:30:00'),
    actualCost: 120,
    estimatedCost: 100,
    notes: 'Auburn Handyman replaced fan motor. Unit tested and working properly.',
    createdAt: new Date('2026-08-20T10:10:00'),
    updatedAt: new Date('2026-08-25T11:30:00'),
  },
  {
    id: 'maint_008',
    unitId: 'unit_rv1_301',
    requestedBy: 'tenant_005',
    title: 'Garbage disposal not working — humming but not spinning',
    description:
      'The garbage disposal hums when switched on but the grinding mechanism doesn\'t spin. It\'s not jammed as far as I can tell — the reset button didn\'t help.',
    priority: MaintenancePriority.MEDIUM,
    status: MaintenanceStatus.OPEN,
    category: 'Appliance',
    vendorId: 'vendor_007',
    estimatedCost: 130,
    createdAt: new Date('2026-09-02T18:22:00'),
    updatedAt: new Date('2026-09-02T18:22:00'),
  },
  {
    id: 'maint_009',
    unitId: 'unit_jac_c01',
    requestedBy: 'user_manager_001',
    title: 'Exterior fence panel damaged — possible storm damage',
    description:
      'Two fence panels on the south side of J-C01 are leaning at an angle and one has a cracked post. Likely from the recent thunderstorm. Safety concern for the yard.',
    priority: MaintenancePriority.MEDIUM,
    status: MaintenanceStatus.OPEN,
    category: 'Structural',
    vendorId: 'vendor_008',
    estimatedCost: 300,
    createdAt: new Date('2026-08-30T08:00:00'),
    updatedAt: new Date('2026-08-30T08:00:00'),
  },
  {
    id: 'maint_010',
    unitId: 'unit_rv3_3a',
    requestedBy: 'tenant_004',
    title: 'Pest sighting — roaches in kitchen cabinet under sink',
    description:
      'Spotted 3-4 cockroaches in the cabinet under the kitchen sink. Found droppings inside the cabinet. This is a new unit — concerned about an infestation.',
    priority: MaintenancePriority.MEDIUM,
    status: MaintenanceStatus.IN_PROGRESS,
    category: 'Pest',
    vendorId: 'vendor_005',
    scheduledAt: new Date('2026-09-08T10:00:00'),
    estimatedCost: 200,
    notes: 'Tiger Pest Control scheduled for full kitchen treatment Sept 8.',
    createdAt: new Date('2026-09-03T20:05:00'),
    updatedAt: new Date('2026-09-04T09:00:00'),
  },

  // ── LOW (5) ─────────────────────────────────────────────────────────────────
  {
    id: 'maint_011',
    unitId: 'unit_rv1_102',
    requestedBy: 'tenant_002',
    title: 'Bedroom window blind broken — cord snapped',
    description:
      'The cord on the second bedroom window blind snapped and the blind is stuck halfway down. Would like it replaced before moving out.',
    priority: MaintenancePriority.LOW,
    status: MaintenanceStatus.OPEN,
    category: 'General',
    estimatedCost: 45,
    createdAt: new Date('2026-08-22T14:00:00'),
    updatedAt: new Date('2026-08-22T14:00:00'),
  },
  {
    id: 'maint_012',
    unitId: 'unit_jac_a02',
    requestedBy: 'tenant_011',
    title: 'Landscaping — overgrown hedges blocking porch light',
    description:
      'The hedges along the front walkway have grown tall enough to block the porch light. Getting dark when arriving home at night. Would appreciate trimming.',
    priority: MaintenancePriority.LOW,
    status: MaintenanceStatus.OPEN,
    category: 'Landscaping',
    vendorId: 'vendor_006',
    estimatedCost: 80,
    createdAt: new Date('2026-08-18T17:30:00'),
    updatedAt: new Date('2026-08-18T17:30:00'),
  },
  {
    id: 'maint_013',
    unitId: 'unit_bab_b03',
    requestedBy: 'tenant_008',
    title: 'Dripping bathroom faucet — master bath',
    description:
      'The faucet in the master bathroom drips steadily even when fully closed. Not urgent but it\'s annoying and wastes water.',
    priority: MaintenancePriority.LOW,
    status: MaintenanceStatus.COMPLETED,
    category: 'Plumbing',
    vendorId: 'vendor_001',
    scheduledAt: new Date('2026-08-15T08:00:00'),
    completedAt: new Date('2026-08-15T09:15:00'),
    actualCost: 95,
    estimatedCost: 100,
    notes: 'Replaced worn cartridge. Faucet tested — no drip.',
    createdAt: new Date('2026-08-10T11:00:00'),
    updatedAt: new Date('2026-08-15T09:15:00'),
  },
  {
    id: 'maint_014',
    unitId: 'unit_rv1_202',
    requestedBy: 'tenant_004',
    title: 'Touch-up paint needed — scuff marks on hallway wall',
    description:
      'There are scuff marks on the hallway wall near the front door from moving furniture in. Would like touch-up paint to freshen it up.',
    priority: MaintenancePriority.LOW,
    status: MaintenanceStatus.OPEN,
    category: 'General',
    estimatedCost: 30,
    createdAt: new Date('2026-08-12T13:45:00'),
    updatedAt: new Date('2026-08-12T13:45:00'),
  },
  {
    id: 'maint_015',
    unitId: 'unit_jac_a03',
    requestedBy: 'tenant_012',
    title: 'Garage door opener remote not working',
    description:
      'The remote for the garage door opener stopped working. I replaced the battery and it still won\'t respond. The wall button works fine.',
    priority: MaintenancePriority.LOW,
    status: MaintenanceStatus.COMPLETED,
    category: 'General',
    vendorId: 'vendor_004',
    scheduledAt: new Date('2026-08-29T14:00:00'),
    completedAt: new Date('2026-08-29T14:45:00'),
    actualCost: 55,
    estimatedCost: 60,
    notes: 'Reprogrammed remote — working correctly. No parts needed.',
    createdAt: new Date('2026-08-26T09:30:00'),
    updatedAt: new Date('2026-08-29T14:45:00'),
  },
]
