import { Vendor } from '@/types'

export let vendors: Vendor[] = [
  {
    id: 'vendor_001',
    name: 'Auburn Plumbing Co.',
    trade: 'plumbing',
    contactName: 'Ray Hollis',
    email: 'ray@auburnplumbing.com',
    phone: '(334) 555-1101',
    address: '210 Glenn Ave, Auburn, AL 36830',
    licenseNumber: 'AL-PLB-88421',
    insured: true,
    rating: 4.8,
    notes: 'Preferred plumbing vendor — fast response times, fair pricing. Available for emergency calls.',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'vendor_002',
    name: 'Lee County Electric',
    trade: 'electrical',
    contactName: 'Danny Marsh',
    email: 'service@leecountyelectric.com',
    phone: '(334) 555-1102',
    address: '455 Opelika Rd, Auburn, AL 36830',
    licenseNumber: 'AL-ELC-55320',
    insured: true,
    rating: 4.6,
    notes: 'Licensed master electrician on staff. Good for panel work and code compliance inspections.',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'vendor_003',
    name: 'Capital HVAC Services',
    trade: 'hvac',
    contactName: 'Brenda Tate',
    email: 'brenda@capitalhvac.com',
    phone: '(334) 555-1103',
    address: '820 Wire Rd, Auburn, AL 36832',
    licenseNumber: 'AL-HVAC-19072',
    insured: true,
    rating: 4.7,
    notes: 'Handles all HVAC brands. Offers maintenance contracts for portfolio discounts.',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'vendor_004',
    name: 'Auburn Handyman Services',
    trade: 'general',
    contactName: 'Skip Owens',
    email: 'skip@auburnhandyman.com',
    phone: '(334) 555-1104',
    address: '112 N College St, Auburn, AL 36830',
    insured: true,
    rating: 4.4,
    notes: 'General repairs, door hardware, locks, painting, minor carpentry. Very reliable for quick jobs.',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'vendor_005',
    name: 'Tiger Pest Control',
    trade: 'pest',
    contactName: 'Luis Ferreira',
    email: 'service@tigerpest.com',
    phone: '(334) 555-1105',
    address: '330 East Samford Ave, Auburn, AL 36830',
    licenseNumber: 'AL-PEST-44210',
    insured: true,
    rating: 4.5,
    notes: 'Quarterly treatment contracts available. Handles roaches, ants, termites, and rodents.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'vendor_006',
    name: 'Auburn Landscaping',
    trade: 'landscaping',
    contactName: 'Pete Granger',
    email: 'pete@auburnlandscaping.net',
    phone: '(334) 555-1106',
    address: '90 Shug Jordan Pkwy, Auburn, AL 36830',
    insured: true,
    rating: 4.3,
    notes: 'Weekly lawn service, hedge trimming, seasonal cleanup. Gives bulk rate for multiple properties.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'vendor_007',
    name: 'Eagle Appliance Repair',
    trade: 'appliance',
    contactName: 'Deb Fowler',
    email: 'deb@eagleappliance.com',
    phone: '(334) 555-1107',
    address: '560 Opelika Rd, Ste 4, Auburn, AL 36830',
    insured: true,
    rating: 4.5,
    notes: 'Repairs all major appliance brands — refrigerators, washers, dryers, dishwashers, disposals. Carries common parts in van.',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'vendor_008',
    name: 'Davis Construction',
    trade: 'structural',
    contactName: 'Wayne Davis',
    email: 'wayne@davisconstruction.com',
    phone: '(334) 555-1108',
    address: '2100 Sandstone Dr, Auburn, AL 36830',
    licenseNumber: 'AL-GC-72940',
    insured: true,
    rating: 4.6,
    notes: 'Licensed general contractor. Use for structural repairs, fencing, decks, and larger renovation projects.',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
]
